// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsvBOL4KV_vuttC4Isfg4wnoEMtlbx9sE',
    appId: '1:569226026728:web:d893d8f631b97a27d5335d',
    messagingSenderId: '569226026728',
    projectId: 'shuroo-job-post',
    authDomain: 'shuroo-job-post.firebaseapp.com',
    storageBucket: 'shuroo-job-post.firebasestorage.app',
    measurementId: 'G-ERQCREE7YK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT-5KQID0zHf10MKwOT9Exdnun7Dk6IIk',
    appId: '1:569226026728:android:74fda0bd094c6b9bd5335d',
    messagingSenderId: '569226026728',
    projectId: 'shuroo-job-post',
    storageBucket: 'shuroo-job-post.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXNKIhEHYfjfz4EKt38GuAzwDljXpJEPI',
    appId: '1:569226026728:ios:bae357d4c8bb1132d5335d',
    messagingSenderId: '569226026728',
    projectId: 'shuroo-job-post',
    storageBucket: 'shuroo-job-post.firebasestorage.app',
    iosBundleId: 'com.shuroo.shuroo.shuroo',
  );
}
